Repository eBay/ebayui-core-react, pull requests merged in 2024-10, with the labels that each got.

#364 [Update] Button Docs
  src/ebay-button/README.md
Labels: documentation

#371 feat(EbaySvg): Support list of icons to render
  scripts/__tests__/__snapshots__/update-icons.spec.ts.snap
  scripts/update-icons-helpers.js
  scripts/update-icons.js
  src/ebay-icon/icon.tsx
  src/ebay-svg/README.md
  src/ebay-svg/__tests__/index.stories.tsx
  src/ebay-svg/svg.tsx
  src/ebay-svg/symbols.tsx
Labels: tech debt

#373 fix(Icon): Add react import on icon symbols
  scripts/__tests__/__snapshots__/update-icons.spec.ts.snap
  scripts/update-icons-helpers.js
  src/ebay-svg/symbols.tsx
Labels: bug
